### ISSUE TITLE
Bot failed navigating to Zone Goliath on Arcanum Sanbox

### ISSUE THREAD

**Issue by Ekytfy** [steve1316/granblue-automation-android#17]
Here's the debug log

>00:00:00 ####################
>00:00:00 ####################
> 00:00:00 [FARM] Starting Farming Mode for Arcarum Sandbox.
>
>00:00:00 [FARM] Farming 999x Earth Verum Proof at Vestige of Truth.
>00:00:00 ####################
>00:00:00 ####################
>
>00:00:00 [ARCARUM.SANDBOX] Now beginning navigation to Zone Goliath...
>
>00:00:00 [DEBUG] Starting process to find the HOME header image...
>00:00:01 [DEBUG] Match found with 0.991 >= 0.8 at Point {20.0, 103.0} using scale: 1.0.
>00:00:01 [DEBUG] Current location confirmed to be at HOME.
>00:00:01 [INFO] Bot is already at the Home screen.
>
>00:00:01 [DEBUG] Starting process to find the HOME_MENU button image...
>00:00:03 [DEBUG] Match found with 0.92 >= 0.8 at Point {931.0, 84.0} using scale: 1.0.
>00:00:03 [DEBUG] Found the HOME_MENU at {1004.0, 135.0}.
>00:00:03 [DEBUG] Now attempting to find and click the "arcarum_banner" button.
>
>00:00:03 [DEBUG] Starting process to find the ARCARUM_BANNER button image...
>00:00:05 [DEBUG] Match not found with 0.14 not >= 0.8 at Point {445.0, 1879.0} using scale 1.0.
>00:00:05 [WARNING] Failed to find the ARCARUM_BANNER button.
>00:00:06 [DEBUG] Now attempting to find and click the "arcarum_banner" button.
>
>00:00:06 [DEBUG] Starting process to find the ARCARUM_BANNER button image...
>00:00:07 [DEBUG] Match found with 0.987 >= 0.8 at Point {330.0, 1825.0} using scale: 1.0.
>00:00:07 [DEBUG] Found the ARCARUM_BANNER at {542.0, 1856.0}.
>00:00:07 [DEBUG] Adding an additional delay of 0.956s...
>
>00:00:10 [DEBUG] Starting process to find the ARCARUM_SANDBOX header image...
>00:00:10 [DEBUG] Match not found with 0.352 not >= 0.8 at Point {537.0, 2039.0} using scale 1.0.
>00:00:11 [DEBUG] Match not found with 0.352 not >= 0.8 at Point {537.0, 2039.0} using scale 1.0.
>00:00:12 [DEBUG] Match found with 0.998 >= 0.8 at Point {369.0, 96.0} using scale: 1.0.
>00:00:12 [DEBUG] Current location confirmed to be at ARCARUM_SANDBOX.
>00:00:14 [DEBUG] Now attempting to find and click the "arcarum_sandbox_zone_goliath" button.
>
>00:00:14 [DEBUG] Starting process to find the ARCARUM_SANDBOX_ZONE_GOLIATH button image...
>00:00:16 [DEBUG] Match not found with 0.79 not >= 0.8 at Point {42.0, 1170.0} using scale 1.0.
>00:00:19 [DEBUG] Match not found with 0.79 not >= 0.8 at Point {42.0, 1173.0} using scale 1.0.
>00:00:20 [DEBUG] Match not found with 0.79 not >= 0.8 at Point {42.0, 1173.0} using scale 1.0.
>00:00:22 [DEBUG] Match not found with 0.79 not >= 0.8 at Point {42.0, 1173.0} using scale 1.0.
>00:00:24 [DEBUG] Match not found with 0.79 not >= 0.8 at Point {42.0, 1173.0} using scale 1.0.
>00:00:24 [WARNING] Failed to find the ARCARUM_SANDBOX_ZONE_GOLIATH button.
>00:00:26 [ARCARUM.SANDBOX] Now determining if bot is starting all the way at the left edge of the Zone...
>00:00:26 [DEBUG] Now attempting to find and click the "arcarum_sandbox_left_arrow" button.
>
>00:00:26 [DEBUG] Starting process to find the ARCARUM_SANDBOX_LEFT_ARROW button image...
>00:00:28 [DEBUG] Match not found with 0.619 not >= 0.8 at Point {440.0, 1289.0} using scale 1.0.
>00:00:28 [ARCARUM.SANDBOX] Left edge of the Zone has been reached.
>00:00:28 [ARCARUM.SANDBOX] Now beginning navigation to Vestige of Truth inside Zone Goliath...
>00:00:28 [DEBUG] Now attempting to find and click the "arcarum_sandbox_right_arrow" button.
>
>00:00:28 [DEBUG] Starting process to find the ARCARUM_SANDBOX_RIGHT_ARROW button image...
>00:00:29 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:31 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:32 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:34 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:36 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:36 [WARNING] Failed to find the ARCARUM_SANDBOX_RIGHT_ARROW button.
>00:00:37 [DEBUG] Now attempting to find and click the "arcarum_sandbox_right_arrow" button.
>
>00:00:37 [DEBUG] Starting process to find the ARCARUM_SANDBOX_RIGHT_ARROW button image...
>00:00:38 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:40 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 742.0} using scale 1.0.
>00:00:42 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 704.0} using scale 1.0.
>00:00:44 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 704.0} using scale 1.0.
>00:00:45 [DEBUG] Match not found with 0.653 not >= 0.8 at Point {473.0, 704.0} using scale 1.0.
>00:00:45 [WARNING] Failed to find the ARCARUM_SANDBOX_RIGHT_ARROW button.
>
>00:00:46 [DEBUG] Starting process to find the HOME_MENU button image...
>00:00:48 [DEBUG] Match not found with 0.495 not >= 0.8 at Point {931.0, 49.0} using scale 1.0.
>00:00:49 [DEBUG] Match not found with 0.495 not >= 0.8 at Point {931.0, 49.0} using scale 1.0.
>00:00:52 [DEBUG] Match not found with 0.54 not >= 0.8 at Point {931.0, 64.0} using scale 1.0.
>00:00:54 [DEBUG] Match not found with 0.566 not >= 0.8 at Point {931.0, 64.0} using scale 1.0.
>00:00:56 [DEBUG] Match not found with 0.663 not >= 0.8 at Point {931.0, 75.0} using scale 1.0.
>00:00:56 [WARNING] Failed to find the HOME_MENU button.
>00:00:56 GAA encountered an Exception: java.lang.NullPointerException
>	at com.steve1316.granblue_automation_android.bot.game_modes.ArcarumSandbox.navigateToM>ission(ArcarumSandbox.kt:95)
>
>	at com.steve1316.granblue_automation_android.bot.game_modes.ArcarumSandbox.navigateToMission$default(ArcarumSandbox.kt:75)
>	at 
> com.steve1316.granblue_automation_android.bot.game_modes.ArcarumSandbox.navigateToZone(ArcarumSandbox.kt:197)
>	at com.steve1316.granblue_automation_android.bot.game_modes.ArcarumSandbox.start(ArcarumSandbox.kt:226)
>	at com.steve1316.granblue_automation_android.b>ot.Game.startFarmingMode(Game.kt:1095)
>	at com.steve1316.granblue_automation_android.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:132)
>	at com.steve1316.granblue_automation_android.utils.BotService$onCreate$1$onTouch$1.invoke(BotService.kt:110)
>	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
>
>Now saving Message Log to file named "log @ 2022-02-14 20:17:11" at /storage/emulated/0/Android/data/com.steve1316.granblue_automation_android/files/logs

**Comment by steve1316** [comment]
Have not encountered this while farming Vestige of Truth in v3.5.1 so hopefully it is fixed for you.

**Comment by Ekytfy** [comment]
Already updated to the latest version and the bot still failed navigating to there

**Comment by steve1316** [comment]
Do you happen to know at what screen does the bot stop at? Looking at your message log posted above, it seems that it got to the Replicard Sandbox page with the 4 Zone options and it got stuck there.

**Comment by Ekytfy** [comment]
> Do you happen to know at what screen does the bot stop at? Looking at your message log posted above, it seems that it got to the Replicard Sandbox page with the 4 Zone options and it got stuck there.

This screen 
![Screenshot_20220217_171538_8d34a3f5cd408bc7fb0e30dd00634bdd](https://user-images.githubusercontent.com/67878387/154455055-9b8c9256-86b4-4732-84ce-a8e25890de44.jpg)

**Comment by steve1316** [comment]
I cant seem to replicate your problem on my end. Unfortunately I do not know how to conitnue on this issue.

**Comment by Ekytfy** [comment]
Reinstalling the app seems to fix this for me, also is it possible to print the app version to the message log? That way we know if the app is already updated or not. Thanks a bunch !
@steve1316

**Comment by steve1316** [comment]
Awesome! I have also incorporated your feedback for the next release 👍
